feat: More Open-Sauced branding
open-sauced/docs.opensauced.pizza pull request #46
Opened 2022-10-01 10:33 UTC by Deadreyo

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds more of the Open Sauce branding and graphical identity to the website, through images and icons.

## Related Tickets & Documents
Fixes #32 

## Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/52013393/193405271-b767d3ab-debe-481e-958e-280df1aa7c66.png)
![image](https://user-images.githubusercontent.com/52013393/193405276-36c5a990-2332-4f3c-8add-c868ff3fa5d1.png)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
Nothing

## [optional] What gif best describes this PR or how it makes you feel?

2022-10-01 17:30 UTC, Deadreyo commented
This failing check is not a result of my work nor is it related to it in any way. My work only touched the styling and the text content of the website.

Awaiting reviewing. @bdougie @0-vortex

2022-10-01 17:35 UTC, 0-vortex requested changes
Added some comments for very minor changes, looks good to me after that! 👍 

cc @bdougie what do you think?

2022-10-01 17:35 UTC, 0-vortex commented on docs/introduction.md
> +Open Sauced provides guidance for new contributors finding their next contribution. Our approach towards onboarding offers a way to trdack contributions through a GitHub powered dashboard.
typo here :P

2022-10-01 17:35 UTC, 0-vortex commented on docusaurus.config.js
> +          title: 'More ',
no need for space here

2022-10-01 17:36 UTC, 0-vortex commented
> This failing check is not a result of my work nor is it related to it in any way. My work only touched the styling and the text content of the website.
> 
> Awaiting reviewing. @bdougie @0-vortex

Hey don't worry about that, I noticed the action failing and silently ignored 😅

2022-10-01 17:39 UTC, Deadreyo commented
Ok fixed

2022-10-01 18:46 UTC, 0-vortex approved these changes
LGTM! 👍 I'll let @bdougie have the last word design wise, as fas as code is concerned, simple, clean and timely PR, great first contribution! 🍕

2022-10-05 21:32 UTC, bdougie commented
I think it looks good and adds flair. Also timely. Opened two related issues.

https://github.com/open-sauced/docs.opensauced.pizza/issues/47
https://github.com/open-sauced/docs.opensauced.pizza/issues/48

2022-10-05 21:32 UTC, bdougie approved these changes

2022-10-05 21:33 UTC, merged