fix: improve intro to contributing
open-sauced/docs.opensauced.pizza pull request #63
Opened 2023-03-14 20:12 UTC by diivi

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR fixes 3/4 points from #36. Considering the 2nd point, `In the "Testing" section...` is not a big issue.

- [x] In the ["Setup" section](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#setup) a first-time contributor might not know (or might appreciate a refresher) on how to fork and clone a repo.
- [x] In the ["Issues" section](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues), the sentence "... please assign yourself by commenting on the following word .take" is maybe slightly confusing.
- [ ] `In the "Pull Requests" section...` This entire section should probably be changed, as mentioned [here](https://github.com/open-sauced/docs.opensauced.pizza/issues/36#issuecomment-1115377316), will do this after some more discussion.
- [x] In the ["Funding" section](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#funding), the link to funding.yml is broken, and seems to possibly not be applicable currently anyway.

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

2023-03-14 22:43 UTC, bdougie commented on docs/contributing/introduction-to-contributing.md
> +1. [Fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the main repository at [open-sauced/insights](https://github.com/open-sauced/insights) to your own GitHub account.
This might not always be true. We also encourage new contributors to contribute to open-sauced/hot instead.

2023-03-18 03:19 UTC, bdougie requested changes
one fix. need to stop pointing to open-sauced/open-sauced since it will soon be deprecated.

2023-03-18 03:19 UTC, bdougie commented on docs/contributing/introduction-to-contributing.md
> +If you are contributing to the project for the first time, please consider joining checking the [bug](https://github.com/open-sauced/open-sauced/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9B+
```suggestion
If you are contributing to the project for the first time, please consider joining checking the [bug](https://github.com/open-sauced/open-sauced/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9B+bug%22) or [good first issue](https://github.com/open-sauced/hot/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) labels.
```

2023-03-18 12:25 UTC, diivi commented on docs/contributing/introduction-to-contributing.md
> +If you are contributing to the project for the first time, please consider joining checking the [bug](https://github.com/open-sauced/open-sauced/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9B+
```suggestion
If you are contributing to the project for the first time, please consider checking the [bug](https://github.com/open-sauced/hot/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9B+bug%22) or [good first issue](https://github.com/open-sauced/hot/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) labels.
```

2023-03-18 12:49 UTC, bdougie approved these changes

2023-03-18 12:49 UTC, merged

2023-03-18 13:03 UTC, AmanNegi commented
Congrats 🎉 @diivi